package com.pe4king.renderers.pytest

/**
 * Templates for pytest test generation.
 */
object PytestTemplates {

    val FILE_HEADER = """
        |\"\"\"
        |API Tests generated by Pe4King
        |Source: {source}
        |Generated: {generatedAt}
        |\"\"\"
        |
        |import pytest
        |import requests
        |import re
        |from typing import Any, Dict
        |
        |
        |BASE_URL = "{baseUrl}"
        |
        |
        |# ============================================================================
        |# API Tests
        |# ============================================================================
        |""".trimMargin()

    val TEST_FUNCTION = """
        |
        |def {testName}(api_client):
        |    \"\"\"
        |    {displayName}
        |    Endpoint: {method} {path}
        |    \"\"\"
        |    # Arrange
        |{arrange}
        |
        |    # Act
        |    response = {request}
        |
        |    # Assert
        |    assert response.status_code == {statusCode}
        |{assertions}
        |""".trimMargin()

    val NEGATIVE_TEST = """
        |
        |@pytest.mark.skip(reason="{disabledReason}")
        |def {testName}(api_client):
        |    \"\"\"
        |    {displayName}
        |    Expected: {statusCode}
        |    \"\"\"
        |    # TODO: Implement negative test
        |    pass
        |""".trimMargin()

    val CONFTEST = """
        |\"\"\"
        |Pytest configuration and fixtures.
        |\"\"\"
        |
        |import pytest
        |import requests
        |import os
        |from typing import Any, Dict
        |
        |
        |def pytest_configure(config):
        |    \"\"\"Configure pytest.\"\"\"
        |    config.addinivalue_line("markers", "smoke: mark test as smoke test")
        |    config.addinivalue_line("markers", "regression: mark test as regression test")
        |
        |
        |@pytest.fixture(scope="session")
        |def base_url() -> str:
        |    \"\"\"Base URL from environment or default.\"\"\"
        |    return os.getenv("API_BASE_URL", "{baseUrl}")
        |
        |
        |@pytest.fixture(scope="session")
        |def auth_token() -> str:
        |    \"\"\"Auth token from environment.\"\"\"
        |    return os.getenv("API_TOKEN", "")
        |
        |
        |@pytest.fixture(scope="session")
        |def headers(auth_token: str) -> Dict[str, str]:
        |    \"\"\"Common headers for all requests.\"\"\"
        |    h = {
        |        "Content-Type": "application/json",
        |        "Accept": "application/json",
        |    }
        |    if auth_token:
        |        h["Authorization"] = f"Bearer {auth_token}"
        |    return h
        |
        |
        |@pytest.fixture
        |def api_client(base_url: str, headers: Dict[str, str]):
        |    \"\"\"Simple API client fixture.\"\"\"
        |    class ApiClient:
        |        def __init__(self):
        |            self.base_url = base_url
        |            self.headers = headers
        |
        |        def get(self, path: str, **kwargs) -> requests.Response:
        |            return requests.get(f"{self.base_url}{path}", headers=self.headers, **kwargs)
        |
        |        def post(self, path: str, json: Any = None, **kwargs) -> requests.Response:
        |            return requests.post(f"{self.base_url}{path}", headers=self.headers, json=json, **kwargs)
        |
        |        def put(self, path: str, json: Any = None, **kwargs) -> requests.Response:
        |            return requests.put(f"{self.base_url}{path}", headers=self.headers, json=json, **kwargs)
        |
        |        def patch(self, path: str, json: Any = None, **kwargs) -> requests.Response:
        |            return requests.patch(f"{self.base_url}{path}", headers=self.headers, json=json, **kwargs)
        |
        |        def delete(self, path: str, **kwargs) -> requests.Response:
        |            return requests.delete(f"{self.base_url}{path}", headers=self.headers, **kwargs)
        |
        |    return ApiClient()
        |""".trimMargin()

    val REQUIREMENTS = """
        |pytest>=7.0.0
        |requests>=2.28.0
        |""".trimMargin()
}
