package com.pe4king.renderers.restassured

/**
 * Java code templates for REST Assured test generation.
 */
object RestAssuredTemplates {

    val FILE_HEADER = """
package {javaPackage};

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

/**
 * Generated API tests for {specTitle}
 * Source: {source}
 * Generated: {generatedAt}
 */
@TestMethodOrder(OrderAnnotation.class)
public class ApiTest {

    private static final String BASE_URL = "{baseUrl}";

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

""".trimIndent()

    val FILE_FOOTER = """
}
""".trimIndent()

    val TEST_METHOD = """

    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {testName}() {
        given()
            .contentType(ContentType.JSON)
{headers}{pathParams}{queryParams}{body}        .when()
            .{method}("{path}")
        .then()
            .statusCode({statusCode})
{assertions}            ;
    }
""".trimIndent()

    val NEGATIVE_TEST = """

    @Test
    @Disabled("{disabledReason}")
    @DisplayName("{displayName}")
    void {testName}() {
        // TODO: Implement negative test
        // Expected status: {statusCode}
    }
""".trimIndent()

    // ============================================================================
    // Layer 1: Base Classes (Static Framework)
    // ============================================================================

    val BASE_TEST = """
package {package}.base;

import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.BeforeAll;

/**
 * Base test class with common setup.
 * All test classes should extend this.
 */
public abstract class BaseTest {

    protected static RequestSpecification spec;
    protected static RequestSpecification specNoAuth;

    @BeforeAll
    public static void setupSpec() {
        String baseUrl = System.getenv().getOrDefault("API_BASE_URL", "{baseUrl}");
        String token = System.getenv().getOrDefault("API_TOKEN", "");

        specNoAuth = new RequestSpecBuilder()
            .setBaseUri(baseUrl)
            .setContentType(ContentType.JSON)
            .setAccept(ContentType.JSON)
            .build();

        RequestSpecBuilder specBuilder = new RequestSpecBuilder()
            .setBaseUri(baseUrl)
            .setContentType(ContentType.JSON)
            .setAccept(ContentType.JSON);

        if (!token.isEmpty()) {
            specBuilder.addHeader("Authorization", "Bearer " + token);
        }

        spec = specBuilder.build();
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
}
""".trimIndent()

    val BASE_CLIENT = """
package {package}.base;

import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static io.restassured.RestAssured.given;

/**
 * Base API client with common functionality.
 * All API clients should extend this.
 */
public abstract class BaseClient {

    protected final RequestSpecification spec;

    public BaseClient(RequestSpecification spec) {
        this.spec = spec;
    }

    protected Response get(String path) {
        return given().spec(spec).get(path);
    }

    protected Response post(String path, Object body) {
        return given().spec(spec).body(body).post(path);
    }

    protected Response put(String path, Object body) {
        return given().spec(spec).body(body).put(path);
    }

    protected Response patch(String path, Object body) {
        return given().spec(spec).body(body).patch(path);
    }

    protected Response delete(String path) {
        return given().spec(spec).delete(path);
    }
}
""".trimIndent()

    // ============================================================================
    // Layer 2: API Clients (Generated per Tag)
    // ============================================================================

    val API_CLIENT_HEADER = """
package {package}.clients;

import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import {package}.base.BaseClient;
import static io.restassured.RestAssured.given;

import java.util.Map;

/**
 * API Client for {tag} endpoints.
 * Generated by Pe4King
 */
public class {className} extends BaseClient {

    public {className}(RequestSpecification spec) {
        super(spec);
    }

""".trimIndent()

    val API_CLIENT_METHOD = """

    /**
     * {description}
     * {method} {path}
     */
    public Response {methodName}({parameters}) {
        return given()
            .spec(spec)
{pathParams}{queryParams}{body}            .{httpMethod}("{path}");
    }
""".trimIndent()

    val API_CLIENT_FOOTER = """
}
""".trimIndent()

    // ============================================================================
    // Layer 3: Test Classes (Using Clients)
    // ============================================================================

    val TEST_CLASS_HEADER = """
package {package}.tests;

import io.restassured.response.Response;
import org.junit.jupiter.api.*;
import static org.hamcrest.Matchers.*;

import java.util.Map;

import {package}.base.BaseTest;
import {package}.clients.{clientClass};

/**
 * API Tests for {tag}
 * Source: {source}
 * Generated: {generatedAt}
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class {className} extends BaseTest {

    private static {clientClass} client;

    @BeforeAll
    static void initClient() {
        BaseTest.setupSpec();
        client = new {clientClass}(spec);
    }

""".trimIndent()

    val TEST_METHOD_WITH_CLIENT = """

    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {testName}() {
        Response response = client.{clientMethod}({callParams});
        response.then()
            .statusCode({statusCode}){assertions};
    }
""".trimIndent()

    val TEST_CLASS_FOOTER = """
}
""".trimIndent()

    // ============================================================================
    // POM.xml
    // ============================================================================

    val POM_XML = """
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>{groupId}</groupId>
    <artifactId>api-tests</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <rest-assured.version>5.4.0</rest-assured.version>
        <junit.version>5.10.1</junit.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${'$'}{rest-assured.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${'$'}{junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.3</version>
            </plugin>
        </plugins>
    </build>
</project>
""".trimIndent()
}
