/**
 * Templates for REST Assured + JUnit 5 test generation.
 */

export const JAVA_FILE_HEADER = `package {package};

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

import java.io.File;
import java.util.Map;
import java.util.List;
import java.util.HashMap;

/**
 * API Tests generated by Pe4King
 * Source: {source}
 * Generated: {generatedAt}
 */
@TestMethodOrder(OrderAnnotation.class)
public class {className} {

    private static RequestSpecification spec;
    private static RequestSpecification specNoAuth;

    @BeforeAll
    static void setup() {
        String baseUrl = System.getenv().getOrDefault("API_BASE_URL", "{baseUrl}");
        String token = System.getenv().getOrDefault("API_TOKEN", "");

        specNoAuth = given()
            .baseUri(baseUrl)
            .contentType(ContentType.JSON)
            .accept(ContentType.JSON);

        spec = given()
            .baseUri(baseUrl)
            .contentType(ContentType.JSON)
            .accept(ContentType.JSON);

        if (!token.isEmpty()) {
            spec = spec.header("Authorization", "Bearer " + token);
        }

        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

`;

export const JAVA_TEST_METHOD = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {methodName}() {
        // Arrange
{arrange}

        // Act & Assert
        given()
            .spec({specName})
{requestBody}
        .when()
            .{httpMethod}({pathExpr})
        .then()
            .log().ifValidationFails()
            .statusCode({statusCode}){assertions}
    }
`;

export const JAVA_MULTIPART_TEST = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {methodName}() {
        // Arrange
{arrange}
        File testFile = new File("test-upload.txt");

        // Act & Assert
        given()
            .spec({specName})
            .contentType("multipart/form-data")
            .multiPart("file", testFile)
{requestBody}
        .when()
            .{httpMethod}({pathExpr})
        .then()
            .log().ifValidationFails()
            .statusCode({statusCode}){assertions}
    }
`;

export const JAVA_NEGATIVE_TEST_404 = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {methodName}() {
        // Act & Assert - Non-existent resource
        given()
            .spec(spec)
{requestBody}
        .when()
            .{httpMethod}({pathExpr})
        .then()
            .log().ifValidationFails()
            .statusCode(404);
    }
`;

export const JAVA_NEGATIVE_TEST_400 = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {methodName}() {
        // Act & Assert - Invalid/empty body
        given()
            .spec(spec)
            .body("{}")
        .when()
            .{httpMethod}({pathExpr})
        .then()
            .log().ifValidationFails()
            .statusCode(anyOf(equalTo(400), equalTo(422)));
    }
`;

export const JAVA_NEGATIVE_TEST_401 = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {methodName}() {
        // Act & Assert - No auth token
        given()
            .spec(specNoAuth)
{requestBody}
        .when()
            .{httpMethod}({pathExpr})
        .then()
            .log().ifValidationFails()
            .statusCode(anyOf(equalTo(401), equalTo(403)));
    }
`;

export const JAVA_FILE_FOOTER = `}
`;

// ============================================================================
// Security/Universal Tests Templates
// ============================================================================

export const JAVA_SECURITY_FILE_HEADER = `package {package};

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

/**
 * Security & Validation Tests generated by Pe4King
 * Source: {source}
 * Generated: {generatedAt}
 *
 * These tests verify common security patterns and input validation
 * that should pass for any well-designed API.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class {className} {

    private static final String BASE_URL = System.getenv().getOrDefault("API_BASE_URL", "{baseUrl}");
    private static final String VALID_TOKEN = System.getenv().getOrDefault("API_TOKEN", "");

    @BeforeAll
    static void setup() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

`;

export const JAVA_AUTH_TEST = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - No authentication")
    void test_{endpoint_name}_no_auth() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
        .when()
            .{method_lower}("{path}")
        .then()
            .statusCode(401);
    }
`;

export const JAVA_INVALID_AUTH_TEST = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - Invalid authentication")
    void test_{endpoint_name}_invalid_auth() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
            .header("Authorization", "{invalid_token}")
        .when()
            .{method_lower}("{path}")
        .then()
            .statusCode(401);
    }
`;

export const JAVA_INJECTION_TEST = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - {test_name}")
    void test_{endpoint_name}_{test_name}() {
        // {description}
        // Payload: {payload}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
{request_args}
        .when()
            .{method_lower}("{path}")
        .then()
            // Should NOT return 200 or 500 (injection should be blocked)
            .statusCode(not(anyOf(equalTo(200), equalTo(500))));
    }
`;

export const JAVA_METHOD_NOT_ALLOWED_TEST = `
    @Test
    @Tag("validation")
    @DisplayName("[{wrong_method}] {path} - Method not allowed (should be {method})")
    void test_{endpoint_name}_method_not_allowed() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
        .when()
            .{wrong_method_lower}("{path}")
        .then()
            .statusCode(405);
    }
`;

export const JAVA_VALIDATION_TEST = `
    @Test
    @Tag("validation")
    @DisplayName("[{method}] {path} - {test_name}")
    void test_{endpoint_name}_{test_name}() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
{request_args}
        .when()
            .{method_lower}("{path}")
        .then()
            .statusCode(anyOf(equalTo(400), equalTo(404), equalTo(422)));
    }
`;

export const JAVA_SCOPE_TEST = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - {test_name}")
    void test_{endpoint_name}_{test_name}() {
        // {description}
        // Wrong OAuth2 scope: {wrong_scope}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer token_with_wrong_scope")
        .when()
            .{method_lower}("{path}")
        .then()
            // Wrong scope should return 403 Forbidden
            .statusCode(403);
    }
`;

export const JAVA_PAGINATION_TEST = `
    @Test
    @Tag("validation")
    @DisplayName("[{method}] {path} - {test_name}")
    void test_{endpoint_name}_{test_name}() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType(ContentType.JSON)
{query_params}
        .when()
            .{method_lower}("{path}")
        .then()
            // Invalid pagination should return 400
            .statusCode(400);
    }
`;

export const JAVA_CONTENT_TYPE_TEST = `
    @Test
    @Tag("validation")
    @DisplayName("[{method}] {path} - {test_name}")
    void test_{endpoint_name}_{test_name}() {
        // {description}
        given()
            .baseUri(BASE_URL)
            .contentType("{content_type}")
            .body("{body}")
        .when()
            .{method_lower}("{path}")
        .then()
            // Wrong content type should return 415 or 400
            .statusCode(anyOf(equalTo(415), equalTo(400)));
    }
`;

// ============================================================================
// Layer 1: Base Classes (Static Framework)
// ============================================================================

export const BASE_TEST_TEMPLATE = `package {package}.base;

import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.BeforeAll;

/**
 * Base test class with common setup.
 * All test classes should extend this.
 */
public abstract class BaseTest {

    protected static RequestSpecification spec;
    protected static RequestSpecification specNoAuth;

    @BeforeAll
    static void setupSpec() {
        String baseUrl = System.getenv().getOrDefault("API_BASE_URL", "{baseUrl}");
        String token = System.getenv().getOrDefault("API_TOKEN", "");

        specNoAuth = new RequestSpecBuilder()
            .setBaseUri(baseUrl)
            .setContentType(ContentType.JSON)
            .setAccept(ContentType.JSON)
            .build();

        RequestSpecBuilder specBuilder = new RequestSpecBuilder()
            .setBaseUri(baseUrl)
            .setContentType(ContentType.JSON)
            .setAccept(ContentType.JSON);

        if (!token.isEmpty()) {
            specBuilder.addHeader("Authorization", "Bearer " + token);
        }

        spec = specBuilder.build();
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
}
`;

export const BASE_CLIENT_TEMPLATE = `package {package}.base;

import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static io.restassured.RestAssured.given;

/**
 * Base API client with common functionality.
 * All API clients should extend this.
 */
public abstract class BaseClient {

    protected final RequestSpecification spec;

    public BaseClient(RequestSpecification spec) {
        this.spec = spec;
    }

    protected Response get(String path) {
        return given().spec(spec).get(path);
    }

    protected Response post(String path, Object body) {
        return given().spec(spec).body(body).post(path);
    }

    protected Response put(String path, Object body) {
        return given().spec(spec).body(body).put(path);
    }

    protected Response patch(String path, Object body) {
        return given().spec(spec).body(body).patch(path);
    }

    protected Response delete(String path) {
        return given().spec(spec).delete(path);
    }
}
`;

// ============================================================================
// Layer 2: API Clients (Generated per Tag)
// ============================================================================

export const API_CLIENT_HEADER = `package {package}.clients;

import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import {package}.base.BaseClient;
import static io.restassured.RestAssured.given;

import java.util.Map;

/**
 * API Client for {tag} endpoints.
 * Generated by Pe4King
 */
public class {className} extends BaseClient {

    public {className}(RequestSpecification spec) {
        super(spec);
    }

`;

export const API_CLIENT_METHOD = `
    /**
     * {description}
     * {method} {path}
     */
    public Response {methodName}({parameters}) {
        return given()
            .spec(spec)
{pathParams}{queryParams}{body}
            .{httpMethod}("{path}");
    }
`;

export const API_CLIENT_FOOTER = `}
`;

// ============================================================================
// Layer 3: Test Classes (Using Clients)
// ============================================================================

export const TEST_CLASS_HEADER = `package {package}.tests;

import io.restassured.response.Response;
import org.junit.jupiter.api.*;
import static org.hamcrest.Matchers.*;

import java.util.Map;

import {package}.base.BaseTest;
import {package}.clients.{clientClass};

/**
 * API Tests for {tag}
 * Source: {source}
 * Generated: {generatedAt}
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class {className} extends BaseTest {

    private static {clientClass} client;

    @BeforeAll
    static void initClient() {
        setupSpec();
        client = new {clientClass}(spec);
    }

`;

export const TEST_METHOD_WITH_CLIENT = `
    @Test
    @Order({order})
    @DisplayName("{displayName}")
    void {testName}() {
        Response response = client.{clientMethod}({callParams});
        response.then()
            .statusCode({statusCode}){assertions};
    }
`;

export const SECURITY_TEST_CLASS_HEADER = `package {package}.tests;

import io.restassured.response.Response;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import static org.hamcrest.Matchers.*;

import java.util.Map;

import {package}.base.BaseTest;
import {package}.clients.{clientClass};

/**
 * Security Tests for {tag}
 * Source: {source}
 * Generated: {generatedAt}
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class {className} extends BaseTest {

    private static {clientClass} client;
    private static {clientClass} clientNoAuth;

    @BeforeAll
    static void initClient() {
        setupSpec();
        client = new {clientClass}(spec);
        clientNoAuth = new {clientClass}(specNoAuth);
    }

`;

export const SECURITY_TEST_NO_AUTH = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - No authentication")
    void test_{endpointName}_no_auth() {
        Response response = clientNoAuth.{clientMethod}({callParams});
        response.then().statusCode(401);
    }
`;

export const SECURITY_TEST_INJECTION = `
    @Test
    @Tag("security")
    @DisplayName("[{method}] {path} - {testName}")
    void test_{endpointName}_{testName}() {
        // Payload: {payload}
        Response response = client.{clientMethod}({callParams});
        response.then()
            .statusCode(not(anyOf(equalTo(200), equalTo(500))));
    }
`;

export const SECURITY_TEST_VALIDATION = `
    @Test
    @Tag("validation")
    @DisplayName("[{method}] {path} - {testName}")
    void test_{endpointName}_{testName}() {
        Response response = client.{clientMethod}({callParams});
        response.then()
            .statusCode(anyOf(equalTo(400), equalTo(404), equalTo(422)));
    }
`;

export const TEST_CLASS_FOOTER = `}
`;

// ============================================================================
// POM.xml
// ============================================================================

export const POM_XML = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>{groupId}</groupId>
    <artifactId>api-tests</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <rest-assured.version>5.4.0</rest-assured.version>
        <junit.version>5.10.1</junit.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>\${rest-assured.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>\${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.3</version>
            </plugin>
        </plugins>
    </build>
</project>
`;
